Improve wine-setup script

diff --git a/cpp/scripts/setup_wine b/cpp/scripts/setup_wine
--- a/cpp/scripts/setup_wine
+++ b/cpp/scripts/setup_wine
@@ -5,8 +5,25 @@ if [ -z "$WINEPREFIX" ]; then
 	exit 1
 fi
 
-# FIXME: support both 32-bit and 64-bit Wine
-wine_path=$(wine winepath -u 'C:\windows\syswow64' 2>>/dev/null)
+if [ ! -f $WINEPREFIX/system.reg ]; then
+	echo "$WINEPREFIX does not seem like a valid Wine Prefix"
+	exit 1
+fi
+
+winedump xaudio2_0.dll | grep 32BIT_MACHINE >> /dev/null 2>&1
+
+if [ $? -eq 0 ]; then
+	wine_exe=wine
+else
+	wine_exe=wine64
+fi
+
+wine_path=$(${wine_exe} winepath -u 'C:\windows\system32' 2>>/dev/null)
+if [ $? -ne 0 ]; then
+	echo "Failed to get winepath for c:\windows\system32 (64-bit vs 32-bit mismatch?)"
+	exit 1;
+fi
+
 dll_path=$(pwd)
 
 function install_dll {
