Skip F3DAudio link for now

diff --git a/cpp/scripts/wine_setup_native b/cpp/scripts/wine_setup_native
--- a/cpp/scripts/wine_setup_native
+++ b/cpp/scripts/wine_setup_native
@@ -38,41 +38,45 @@ function install_dll {
 	fi
 
 	# link dll
-	ln -sf "$dll_path/$name.dll" "$wine_path/$name.dll"
+	if [ $2 -ne 0 ]; then
+		ln -sf "$dll_path/$name.dll" "$wine_path/$name.dll"
 
-	if [ $? -ne 0 ]; then
-		echo "Failed to create link for $name"
-		exit 1
+		if [ $? -ne 0 ]; then
+			echo "Failed to create link for $name"
+			exit 1
+		fi
+
+		echo "$name: done"
+	else
+		echo "Skipping link for $name"
 	fi
-
-	echo "$name: done"
 }
 
-install_dll xaudio2_0 
-install_dll xaudio2_1 
-install_dll xaudio2_2 
-install_dll xaudio2_3 
-install_dll xaudio2_4 
-install_dll xaudio2_5 
-install_dll xaudio2_6 
-install_dll xaudio2_7 
-install_dll xaudio2_8 
-install_dll xaudio2_9 
+install_dll xaudio2_0 1
+install_dll xaudio2_1 1
+install_dll xaudio2_2 1
+install_dll xaudio2_3 1
+install_dll xaudio2_4 1
+install_dll xaudio2_5 1
+install_dll xaudio2_6 1
+install_dll xaudio2_7 1
+install_dll xaudio2_8 1
+install_dll xaudio2_9 1
 
-install_dll x3daudio1_3
-install_dll x3daudio1_4
-install_dll x3daudio1_5 
-install_dll x3daudio1_6
-install_dll x3daudio1_7
+install_dll x3daudio1_3 0
+install_dll x3daudio1_4 0
+install_dll x3daudio1_5 0
+install_dll x3daudio1_6 0
+install_dll x3daudio1_7 0
 
-install_dll xactengine3_0
-install_dll xactengine3_1
-install_dll xactengine3_2
-install_dll xactengine3_3
-install_dll xactengine3_4
-install_dll xactengine3_5
-install_dll xactengine3_6
-install_dll xactengine3_7
+install_dll xactengine3_0 1
+install_dll xactengine3_1 1
+install_dll xactengine3_2 1
+install_dll xactengine3_3 1
+install_dll xactengine3_4 1
+install_dll xactengine3_5 1
+install_dll xactengine3_6 1
+install_dll xactengine3_7 1
 
 ln -sf "$dll_path/FAudio.dll" "$wine_path/FAudio.dll"
 ln -sf "$dll_path/SDL2.dll" "$wine_path/SDL2.dll"
